version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: air ./cmd/main.go -b 0.0.0.0
    env_file:
      - .env
    networks:
      - webNetwork
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - webNetwork
volumes:
  postgres-db:

networks:
  webNetwork:
    driver: bridge